.PHONY: check pdf text-count text-target clean

LATEX_DIR := source/latex

check:
	$(MAKE) -C $(LATEX_DIR) check

pdf:
	$(MAKE) -C $(LATEX_DIR) pdf

text-count:
	$(MAKE) -C $(LATEX_DIR) text-count

text-target:
	$(MAKE) -C $(LATEX_DIR) text-target

clean:
	$(MAKE) -C $(LATEX_DIR) clean
