LATEX_DIR := source/latex

.PHONY: check pdf epub clean

check:
	$(MAKE) -C $(LATEX_DIR) check

pdf:
	$(MAKE) -C $(LATEX_DIR) pdf

epub:
	$(MAKE) -C $(LATEX_DIR) epub

clean:
	$(MAKE) -C $(LATEX_DIR) clean
